### ISSUE TITLE
Not possible to set up

### ISSUE THREAD

**Issue by gotohell32434** [myflashlab/facebook-ANE#16] opened 2015-11-20 20:49 UTC
At one point, we saw a white screen with some diagnostic info.
But that is long gone. 
We followed instructions to precise detail, unfortunately no instructions are provided for the MANIFEST, specifically in terms of what to replace with what.

Also the sample app is expired, so the sample app cannot be made to work. 
It's really sad how much time people are spending on this, and eventually giving up. 

Not just yours, but no ANE libraries work. I've tried them all.

**Comment by myflashlab** [comment] 2015-11-20 20:52
I thought you had the purchased version conflicting with the today's
version in github. Well, if you are working with a fresh download from
github, it does work just fine. We have many users already using it in
their apps.

On Saturday, November 21, 2015, gotohell32434 <notifications@github.com>
wrote:

> At one point, we saw a white screen with some diagnostic info.
> But that is long gone.
> We followed instructions to precise detail, unfortunately no instructions
> are provided for the MANIFEST, specifically in terms of what to replace
> with what.
>
> Also the sample app is expired, so the sample app cannot be made to work.
> It's really sad how much time people are spending on this, and eventually
> giving up.
>
> Not just yours, but no ANE libraries work. I've tried them all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/16>.
>


-- 
Sent from iPhone

**Comment by UmberFunk** [comment] 2015-11-23 20:40
@gotohell32434 did you tried Milkman's goViral? That doesn't work too?

**Comment by gotohell32434** [comment] 2015-11-23 20:51
Milkman actually works/connects, but the functions don¹t work.
Also their example doesn¹t work.

These problems are exacerbated with ANE using Flash CS6.
It does not allow to test with iPhone simulator, and you must rename the
folders containing the certificates every time you publish. And then
re-specify their locations.








From:  Ghelle <notifications@github.com>
Reply-To:  myflashlab/facebook-ANE
<reply+00f35aceda49cd6c3ee187b0b692c55d622e76a41ad69d6092cf00000001126b3ba69
2a169ce070a6b49@reply.github.com>
Date:  Monday, November 23, 2015 at 2:40 PM
To:  myflashlab/facebook-ANE <facebook-ANE@noreply.github.com>
Cc:  Graham <graham@pilchbarnet.com>
Subject:  Re: [facebook-ANE] Not possible to set up (#16)


@gotohell32434 <https://github.com/gotohell32434>  did you tried Milkman's
goViral? That doesn't work too?


Reply to this email directly or view it on GitHub
<https://github.com/myflashlab/facebook-ANE/issues/16#issuecomment-159057886
> .

**Comment by UmberFunk** [comment] 2015-11-23 21:04
I am using AIR SDK 18. No Flash Pro. Also I use older version of this ANE. Before App Invites was added. Looks like it's working. 

This ANE has no GameRequests and I was been forced to do it myself using webview. You can see it in issues. I have posted the code for it. Maybe I have modified it later a little in our game. Let me know if you'll need it.

Also the loading rotating indicator was going off-center sometimes. You can hide it. It is in issues also (closed issues).

**Comment by UmberFunk** [comment] 2015-11-23 21:07
Not sure what you mean by iPhone simulator, but if it is Flash's simulator, I don't think it is possible to test ANEs in this simulator. This is the black part of gamedev. Every time you need to publish to device...

**Comment by myflashlab** [comment] 2015-11-24 06:42
@gotohell32434 I should emphasize that you should not run the extension in simulator. Try debugging and running on a real device. If you can't run it, please ask specific questions and we'll try to help but do not make general false statements like:
> Not just yours, but no ANE libraries work. I've tried them all.

**Comment by myflashlab** [comment] 2015-12-03 19:14
I'm closing this issue now as it seems the problem is solved anyway.

**Closed by myflashlab** 2015-12-03 19:14 UTC
